In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [105]:
df = pd.read_csv("Social_Network_Ads.csv")
print(df.shape)
df.head()

(400, 5)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [106]:
df.sample(7)

      User ID  Gender  Age  EstimatedSalary  Purchased
357  15671387  Female   41            72000          0
96   15710257  Female   35            25000          0
348  15579212    Male   39            77000          0
306  15603942  Female   51           134000          0
89   15682268    Male   35            50000          0
32   15573452  Female   21            16000          0
33   15776733  Female   28            44000          0

In [107]:
df = df.iloc[:, 2:]
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [108]:
X = df.drop("Purchased", axis=1)
Y = df["Purchased"]

X, Y

(     Age  EstimatedSalary
 0     19            19000
 1     35            20000
 2     26            43000
 3     27            57000
 4     19            76000
 ..   ...              ...
 395   46            41000
 396   51            23000
 397   50            20000
 398   36            33000
 399   49            36000

 [400 rows x 2 columns],
 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 395    1
 396    1
 397    1
 398    0
 399    1
 Name: Purchased, Length: 400, dtype: int64)

In [109]:
X_train, X_test, y_train , y_test = train_test_split(X, Y, test_size=0.3, random_state=2)
X_train.shape, X_test.shape

((280, 2), (120, 2))

In [110]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [111]:
scaler.mean_

array([3.77642857e+01, 6.99000000e+04])

In [112]:
X_train

     Age  EstimatedSalary
112   38            61000
209   46            22000
294   35            57000
307   47           113000
345   41            63000
..   ...              ...
299   46           117000
22    48            41000
72    20            23000
15    29            80000
168   29           148000

[280 rows x 2 columns]

In [113]:
X_train_scaled

array([[ 0.02273414, -0.26389006],
       [ 0.79431698, -1.42026223],
       [-0.26660943, -0.38249233],
       [ 0.89076483,  1.2779395 ],
       [ 0.3120777 , -0.20458892],
       [-0.26660943, -0.59004631],
       [-0.26660943, -1.42026223],
       [ 1.46945196, -1.06445541],
       [-0.07371372,  0.12156733],
       [-0.84529656, -0.67899802],
       [-0.07371372,  0.00296506],
       [-0.26660943,  0.09191676],
       [ 0.21562985, -0.3231912 ],
       [-0.26660943,  0.26982017],
       [ 0.11918199,  0.03261563],
       [ 1.95169124,  2.19710712],
       [-1.03819227, -1.47956337],
       [ 0.3120777 ,  0.29947074],
       [ 2.04813909, -1.21270825],
       [-1.13464012, -0.53074518],
       [ 0.21562985,  0.1512179 ],
       [-0.26660943, -0.94585313],
       [-0.65240085,  0.03261563],
       [ 0.21562985,  0.06226619],
       [ 0.40852556, -0.14528779],
       [-1.13464012, -1.12375655],
       [-0.07371372,  2.25640826],
       [ 1.08366054, -0.14528779],
       [ 0.89076483,  1.04073495],
       [-0.07371372,  0.26982017],
       [-0.55595299, -1.5388645 ],
       [-1.13464012, -1.03480484],
       [-0.7488487 ,  1.36689121],
       [ 1.08366054,  0.56632586],
       [ 1.56589982, -1.30165996],
       [ 0.69786912, -1.42026223],
       [-0.65240085, -1.06445541],
       [ 1.1801084 ,  0.53667529],
       [-0.26660943, -1.47956337],
       [-1.6168794 ,  0.53667529],
       [-1.03819227, -1.15340711],
       [-0.07371372,  0.03261563],
       [ 0.3120777 ,  0.06226619],
       [ 0.89076483, -1.39061166],
       [-1.03819227, -0.35284176],
       [-1.80977511,  0.18086847],
       [-1.80977511, -1.4499128 ],
       [ 0.69786912,  1.81164973],
       [-0.07371372,  0.29947074],
       [-1.6168794 ,  0.06226619],
       [-0.65240085,  1.42619234],
       [-0.26660943, -0.26389006],
       [-0.36305728,  1.33724064],
       [ 0.50497341,  1.24828893],
       [-0.65240085,  0.18086847],
       [-1.52043154, -0.44179347],
       [-1.03819227,  0.41807302],
       [ 0.79431698,  0.26982017],
       [ 1.95169124, -0.94585313],
       [ 0.79431698, -0.3231912 ],
       [ 0.21562985,  0.2401696 ],
       [-1.71332725, -0.61969688],
       [-0.26660943,  0.1512179 ],
       [-1.32753583, -1.27200939],
       [-0.26660943, -0.44179347],
       [ 0.11918199,  0.09191676],
       [-0.94174441,  0.44772358],
       [ 2.04813909,  0.38842245],
       [-1.90622296,  0.35877188],
       [ 2.04813909, -0.82725086],
       [ 2.14458695,  1.12968666],
       [ 0.79431698, -1.24235882],
       [ 0.40852556, -0.47144404],
       [ 0.02273414, -0.26389006],
       [ 1.46945196,  0.35877188],
       [-0.17016157, -0.59004631],
       [ 0.21562985, -0.26389006],
       [-0.45950514,  2.34535997],
       [ 0.11918199,  0.21051904],
       [ 0.21562985, -0.67899802],
       [ 0.98721269, -1.09410598],
       [-0.17016157,  0.1512179 ],
       [-0.07371372,  0.29947074],
       [ 0.40852556, -0.50109461],
       [-0.36305728, -1.33131052],
       [ 0.89076483, -0.79760029],
       [-0.94174441,  0.41807302],
       [-0.07371372, -0.44179347],
       [-0.94174441, -0.44179347],
       [-1.80977511,  0.44772358],
       [-0.84529656, -1.24235882],
       [-0.94174441, -0.3231912 ],
       [ 0.98721269,  0.77387984],
       [-1.6168794 , -0.05633608],
       [-1.03819227, -0.35284176],
       [ 0.02273414, -0.56039574],
       [-0.65240085, -0.35284176],
       [-1.13464012, -1.56851507],
       [ 1.95169124, -1.39061166],
       [-0.65240085, -1.62781621],
       [ 0.21562985, -0.38249233],
       [ 0.89076483,  2.19710712],
       [ 1.1801084 , -1.00515427],
       [-0.17016157, -0.53074518],
       [ 1.66234767,  1.78199917],
       [ 1.08366054, -1.24235882],
       [ 0.02273414,  1.2779395 ],
       [-0.45950514, -0.29354063],
       [ 1.66234767, -0.91620257],
       [ 0.3120777 ,  0.50702472],
       [-1.03819227, -1.56851507],
       [ 1.56589982,  1.12968666],
       [-1.52043154,  0.32912131],
       [ 0.02273414, -0.14528779],
       [ 0.11918199, -0.82725086],
       [ 0.21562985,  1.10003609],
       [ 0.40852556, -0.17493835],
       [-0.45950514, -0.02668551],
       [ 1.08366054,  2.10815542],
       [-0.26660943, -0.14528779],
       [-0.7488487 , -0.61969688],
       [ 1.1801084 , -1.47956337],
       [-1.42398369, -1.47956337],
       [ 1.85524338, -0.29354063],
       [ 1.85524338,  0.12156733],
       [ 0.40852556,  0.1512179 ],
       [ 1.27655625, -1.39061166],
       [-0.45950514, -1.24235882],
       [-0.7488487 ,  1.93025201],
       [-0.26660943,  1.12968666],
       [ 0.02273414, -0.59004631],
       [ 0.21562985, -0.14528779],
       [-0.55595299,  1.93025201],
       [-0.94174441,  0.26982017],
       [-1.90622296,  0.47737415],
       [-1.32753583,  0.56632586],
       [ 0.21562985,  0.1512179 ],
       [ 1.37300411, -1.4499128 ],
       [-0.07371372,  0.68492813],
       [ 0.11918199,  1.90060144],
       [-1.71332725, -1.00515427],
       [ 0.21562985, -0.38249233],
       [-1.80977511, -1.33131052],
       [ 0.79431698,  0.53667529],
       [-0.17016157,  1.42619234],
       [-1.03819227,  0.56632586],
       [-1.23108798, -1.09410598],
       [ 1.37300411,  2.01920371],
       [ 0.79431698, -1.12375655],
       [ 0.79431698,  0.12156733],
       [-1.80977511, -1.30165996],
       [ 0.02273414,  1.24828893],
       [ 0.89076483, -0.61969688],
       [ 2.14458695,  0.38842245],
       [ 2.14458695, -0.82725086],
       [ 0.98721269, -1.09410598],
       [ 0.11918199,  1.54479462],
       [-0.94174441,  0.50702472],
       [-1.23108798,  0.26982017],
       [ 0.40852556,  0.59597643],
       [ 0.11918199,  0.1512179 ],
       [ 0.21562985,  0.03261563],
       [ 2.04813909,  2.16745656],
       [-0.07371372, -0.38249233],
       [-0.26660943,  0.80353041],
       [-1.42398369, -0.20458892],
       [ 1.08366054,  0.12156733],
       [ 0.3120777 ,  0.06226619],
       [ 0.11918199,  0.03261563],
       [ 0.98721269, -1.03480484],
       [-0.55595299,  1.48549348],
       [-1.13464012, -1.62781621],
       [ 1.27655625,  2.25640826],
       [-1.42398369, -0.11563722],
       [-1.80977511, -1.50921394],
       [ 0.89076483, -1.18305768],
       [ 2.14458695, -0.70864859],
       [ 0.60142127, -0.91620257],
       [-1.23108798, -1.42026223],
       [-0.45950514, -0.85690143],
       [-0.84529656, -0.26389006],
       [ 1.46945196,  2.16745656],
       [ 0.40852556,  1.01108439],
       [ 0.02273414, -0.44179347],
       [-1.13464012, -1.18305768],
       [-0.7488487 ,  0.56632586],
       [ 0.11918199,  1.07038552],
       [-0.55595299,  1.39654178],
       [ 0.11918199,  1.90060144],
       [ 0.21562985,  2.13780599],
       [ 1.46945196,  1.01108439],
       [-1.71332725,  0.12156733],
       [-0.26660943, -0.50109461],
       [ 0.11918199,  0.77387984],
       [ 0.89076483, -1.33131052],
       [-0.26660943, -0.29354063],
       [ 2.14458695, -1.06445541],
       [ 0.40852556,  0.29947074],
       [-0.17016157,  1.63374632],
       [ 0.79431698, -0.85690143],
       [-0.94174441,  1.57444519],
       [ 0.11918199, -0.26389006],
       [-1.23108798,  0.50702472],
       [ 0.11918199, -0.82725086],
       [ 1.08366054, -1.00515427],
       [ 0.98721269,  1.81164973],
       [-1.42398369, -0.64934745],
       [ 0.98721269, -1.21270825],
       [-1.32753583, -0.44179347],
       [ 0.3120777 ,  0.06226619],
       [-0.26660943, -0.59004631],
       [-0.7488487 ,  1.10003609],
       [ 1.56589982,  1.01108439],
       [-1.03819227,  0.59597643],
       [ 0.40852556,  0.09191676],
       [-0.94174441, -0.3231912 ],
       [ 1.1801084 , -0.76794972],
       [-1.90622296, -0.53074518],
       [ 1.08366054, -1.24235882],
       [ 0.3120777 ,  0.26982017],
       [-0.7488487 , -1.62781621],
       [-0.26660943, -1.33131052],
       [-0.26660943,  0.53667529],
       [ 0.98721269,  1.90060144],
       [-0.65240085, -0.11563722],
       [-0.45950514,  1.2779395 ],
       [ 0.3120777 , -0.53074518],
       [ 1.85524338,  1.54479462],
       [ 1.08366054,  0.47737415],
       [ 2.04813909,  0.18086847],
       [-1.71332725,  0.35877188],
       [-0.17016157, -0.20458892],
       [-0.65240085,  0.56632586],
       [ 1.37300411,  1.30759007],
       [ 1.08366054, -0.91620257],
       [ 1.85524338, -1.09410598],
       [-0.7488487 ,  0.50702472],
       [-1.32753583, -1.12375655],
       [ 0.79431698,  0.35877188],
       [-0.84529656,  0.38842245],
       [-0.7488487 ,  0.29947074],
       [-1.03819227,  1.98955314],
       [-0.07371372,  0.06226619],
       [ 1.37300411,  2.37501053],
       [-0.07371372,  0.1512179 ],
       [-0.07371372,  1.98955314],
       [-0.7488487 ,  0.26982017],
       [-1.13464012,  0.32912131],
       [ 0.3120777 , -0.29354063],
       [ 0.98721269, -1.18305768],
       [ 1.37300411,  0.59597643],
       [-1.52043154, -1.5388645 ],
       [-0.94174441, -0.76794972],
       [-1.13464012,  0.06226619],
       [ 0.40852556, -0.47144404],
       [-1.90622296, -0.76794972],
       [ 0.40852556,  0.26982017],
       [-0.26660943,  0.21051904],
       [-0.55595299,  0.47737415],
       [-0.36305728, -0.79760029],
       [-0.26660943,  0.03261563],
       [-0.07371372,  0.21051904],
       [-0.26660943,  0.1512179 ],
       [ 0.3120777 , -0.56039574],
       [ 0.79431698,  0.77387984],
       [ 0.98721269,  2.01920371],
       [-0.17016157, -0.29354063],
       [-1.03819227, -0.47144404],
       [-0.26660943, -0.35284176],
       [ 0.11918199, -0.3231912 ],
       [-0.26660943, -0.76794972],
       [-0.07371372, -1.09410598],
       [-0.26660943,  0.06226619],
       [ 0.50497341,  1.7523486 ],
       [-0.36305728,  1.24828893],
       [ 0.79431698,  1.39654178],
       [ 0.98721269, -0.85690143],
       [-1.71332725, -1.39061166],
       [-0.84529656,  0.29947074],
       [-0.84529656,  2.3157094 ]])

In [114]:
np.round(X_train.describe(), 1)

         Age  EstimatedSalary
count  280.0            280.0
mean    37.8          69900.0
std     10.4          33786.6
min     18.0          15000.0
25%     30.0          43750.0
50%     37.0          70500.0
75%     46.0          87000.0
max     60.0         150000.0

In [115]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
np.round(X_train_scaled.describe(), 1)

         Age  EstimatedSalary
count  280.0            280.0
mean     0.0              0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.7             -0.8
50%     -0.1              0.0
75%      0.8              0.5
max      2.1              2.4

In [116]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr_scaled = LogisticRegression()

In [117]:
lr.fit(X_train,y_train)
lr_scaled.fit(X_train_scaled,y_train)

LogisticRegression()

In [118]:
y_pred = lr.predict(X_test)
y_pred_scaled = lr_scaled.predict(X_test_scaled)

/Users/tushar/Desktop/Machine Learning/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [119]:
from sklearn.metrics import accuracy_score
print("Actual",accuracy_score(y_test,y_pred))
print("Scaled",accuracy_score(y_test,y_pred_scaled))

Actual 0.8416666666666667
Scaled 0.8416666666666667

In [121]:
print(np.array_equal(y_pred, y_pred_scaled))

True

In [122]:
lr.predict_proba(X_test)[:5]

array([[9.48281816e-01, 5.17181837e-02],
       [9.99597569e-01, 4.02431231e-04],
       [8.94947454e-01, 1.05052546e-01],
       [9.62689902e-01, 3.73100980e-02],
       [5.04566550e-02, 9.49543345e-01]])

In [123]:
lr_scaled.predict_proba(X_test_scaled)[:5]

/Users/tushar/Desktop/Machine Learning/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[9.31519311e-01, 6.84806889e-02],
       [9.99013174e-01, 9.86825842e-04],
       [8.73534701e-01, 1.26465299e-01],
       [9.48329650e-01, 5.16703498e-02],
       [7.37055789e-02, 9.26294421e-01]])