In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv("cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [18]:
df.shape

(8128, 5)

In [19]:
df["brand"].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [20]:
df["fuel"].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [21]:
df["owner"].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

# One Hot Encoding using Pandas

In [22]:
pd.get_dummies(df, columns=["owner", "fuel"],drop_first=True)

,brand,km_driven,selling_price,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,False,False,False,False,True,False,False
1,Skoda,120000,370000,False,True,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,True
3,Hyundai,127000,225000,False,False,False,False,True,False,False
4,Maruti,120000,130000,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,False,False,False,True
8124,Hyundai,119000,135000,True,False,False,False,True,False,False
8125,Maruti,120000,382000,False,False,False,False,True,False,False
8126,Tata,25000,290000,False,False,False,False,True,False,False
8127,Tata,25000,290000,False,False,False,False,True,False,False

# One Hot Encoding using sklearn

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :4], df.iloc[:, -1], test_size=0.2, random_state=2)
X_train.shape, X_test.shape

((6502, 4), (1626, 4))

In [24]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [33]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop="first", dtype=np.int32, sparse_output=False)

X_train_new = ohe.fit_transform(X_train[["fuel", "owner"]])
X_test_new = ohe.transform(X_test[["fuel", "owner"]])

X_train_new.shape

(6502, 7)

In [34]:
np.hstack((X_train[["brand", "km_driven"]], X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

# OHE with Top Categories

In [49]:
counts = df["brand"].value_counts()
threshold = 100
replace = counts[counts <= threshold].index
replace

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [54]:
df["brand"].replace(replace, "uncommon").sample(10)

3617        Maruti
2404          Tata
1578         Honda
5972       Renault
4400    Volkswagen
2502       Hyundai
133       uncommon
7009       Hyundai
5275       Hyundai
2621      uncommon
Name: brand, dtype: object

In [55]:
pd.get_dummies(df["brand"].replace(replace, "uncommon"))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False